--- # To Uninstall httpd software
- name: Uninstall httpd s/w
  hosts: webservers[0]
  user: ansible
  become: yes
  connection: ssh

  tasks:
  - name: Stop httpd on RedHat
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: Uninstall httpd on RedHat
    yum: 
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

