--- # To Install httpd software
- name: Install httpd s/w
  hosts: webservers[0]
  user: ansible
  become: yes
  connection: ssh

  tasks:
  - name: Install httpd on RedHat
    yum: 
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Start httpd on RedHat
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

