--- # Install service
- name: Install software
  hosts: webservers[0]
  user: ansible
  become: true
  connection: ssh

  vars:
    pkgname: httpd

  tasks:
    - name: Install httpd s/w 
      action: yum name='{{pkgname}}' state=latest

    - name: Start httpd service
      action: service name='{{pkgname}}' state=started
